name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "nourddinelearning/nourbuilder"
          install: true

      - name: Get next version tag
        id: version
        run: |
          set -e
          echo "Fetching latest Docker tag..."

          latest=$(curl -s https://hub.docker.com/v2/repositories/${{ vars.DOCKER_USER }}/portfolio/tags | jq -r '.results[].name' | grep '^v' | sort -V | tail -n 1)

          if [ -z "$latest" ]; then
            next_tag="v1"
          else
            number=$(echo $latest | sed 's/v//')
            next=$((number+1))
            next_tag="v$next"
          fi

          echo "Next tag: $next_tag"
          echo "tag=$next_tag" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_USER }}/portfolio:latest
            ${{ vars.DOCKER_USER }}/portfolio:${{ steps.version.outputs.tag }}
