name: Trigger auto deployment for portfolio

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/portfolio-AutoDeployTrigger-0f4ba948-8da4-40d8-af03-c0eee29a610a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PORTFOLIO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PORTFOLIO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PORTFOLIO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.PORTFOLIO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PORTFOLIO_REGISTRY_PASSWORD }}
          containerAppName: portfolio
          resourceGroup: portfilio
          imageToBuild: nourddinelearning@gmail.com/portfolio:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


