name: Trigger auto deployment for portfolio2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/portfolio2-AutoDeployTrigger-5800999d-28d0-495b-996a-f1df16c28c54.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PORTFOLIO2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PORTFOLIO2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PORTFOLIO2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.PORTFOLIO2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PORTFOLIO2_REGISTRY_PASSWORD }}
          containerAppName: portfolio2
          resourceGroup: portfilio
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


